from sqlalchemy import Column, Integer, String, Float, ForeignKey
from sqlalchemy.orm import declarative_base, relationship
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class LearningGoals(Base):
    """
    Represents learning goals for students.

    Attributes:
        id (int): The primary key, auto-incremented.
        learning_goal_names (str): The name of the learning goal.
    
    Relationships:
        session_details (SessionDetails): One-to-many relationship with SessionDetails.
    """
    __tablename__ = 'learning_goals'

    id = Column(Integer, primary_key=True, autoincrement=True)
    learning_goal_names = Column(String, nullable=False)

    # Relationship to SessionDetails
    session_details = relationship("SessionDetails", back_populates="learning_goal")


class SessionDetails(Base):
    """
    Represents session details related to learning goals.

    Attributes:
        id (int): The primary key, auto-incremented.
        learning_goal_id (int): Foreign key linking to LearningGoals.
        student_initial_level (str): The student's initial skill level.
        student_current_level (str): The student's current skill level.

    Relationships:
        learning_goal (LearningGoals): Many-to-one relationship with LearningGoals.
        chat_histories (ChatHistory): One-to-many relationship with ChatHistory.
    """
    __tablename__ = 'session_details'

    id = Column(Integer, primary_key=True, autoincrement=True)
    learning_goal_id = Column(Integer, ForeignKey('learning_goals.id'), nullable=False)
    student_initial_level = Column(String, nullable=False)
    student_current_level = Column(String, nullable=False)

    # Relationship to LearningGoals
    learning_goal = relationship("LearningGoals", back_populates="session_details")
    # Relationship to ChatHistory
    chat_histories = relationship("ChatHistory", back_populates="session")


class ChatHistory(Base):
    """
    Represents the chat history for a learning session.

    Attributes:
        id (int): The primary key, auto-incremented.
        session_id (int): Foreign key linking to SessionDetails.
        llm_response (str): The response generated by the language model.
        learner_response (str): The response provided by the learner.

    Relationships:
        session (SessionDetails): Many-to-one relationship with SessionDetails.
    """
    __tablename__ = 'chat_history'

    id = Column(Integer, primary_key=True, autoincrement=True)
    session_id = Column(Integer, ForeignKey('session_details.id'), nullable=False)
    llm_response = Column(String, nullable=False)
    learner_response = Column(String, nullable=False)

    # Relationship to SessionDetails
    session = relationship("SessionDetails", back_populates="chat_histories")